Fix the following errors: error: no member named 'strerror' in namespace 'std' error: no member named 'memcpy' in namespace 'std' error: no member named 'strchr' in namespace 'std'
all of these require <cstring>. see:
https://en.cppreference.com/w/cpp/string/byte/strerror
https://en.cppreference.com/w/cpp/string/byte/memcpy
https://en.cppreference.com/w/cpp/string/byte/strchr