Fix missing forward declaration of ScriptingRuntime
Otherwise, build fails with musl-based GCC 9.3.0 toolchain when gerbera
is build without JavaScript support:

```
In file included from src/content/layout/layout.cc:28:
src/content/content_manager.h:320:21: error: ‘ScriptingRuntime’ was not declared in this scope
  320 |     std::shared_ptr<ScriptingRuntime> scripting_runtime;
      |                     ^~~~~~~~~~~~~~~~
src/content/content_manager.h:320:37: error: template argument 1 is invalid
  320 |     std::shared_ptr<ScriptingRuntime> scripting_runtime;
      |                                     ^
make[4]: *** [CMakeFiles/libgerbera.dir/build.make:285: CMakeFiles/libgerbera.dir/src/content/layout/layout.cc.o] Error 1
```