fix the following error: error: no member named 'format' in namespace 'fmt'
the comment in fmt/core.h says including 'format' via core is deprectated:
// Using fmt::format via fmt/core.h has been deprecated since version 11
// and now requires an explicit opt in.
#ifdef FMT_DEPRECATED_HEAVY_CORE
#  include "format.h"
#endif